<?php

namespace MarksBundle\Repository;

/**
 * MarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllStudentsFromDiscipline($discipline_id) {
        $qb = $this->createQueryBuilder('m')
            ->select('m.student')
            ->where('m.disciplineId = 16');

        $query = $qb->getQuery();

        return $query->getOneOrNullResult();
    }
}
