<?php

namespace DisciplineBundle\Repository;

/**
 * DisciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplineRepository extends \Doctrine\ORM\EntityRepository
{
    function getStudentDiscipline($id){
        $qb = $this->createQueryBuilder('d')
            ->select('d.name')
            ->leftJoin('d.students','sd')
            ->where('sd = :id')
            ->setParameter('id',$id);

        $query = $qb->getQuery();

        return $query->getResult();
    }

}
